### ISSUE TITLE
Add Support for Node.js 20

### ISSUE THREAD

**Issue by yamadashy** [Milanzor/webpack-watched-glob-entries-plugin#32]
Hello,

Can you please consider adding support for Node.js 20? This would greatly help developers who are transitioning to or already using this version of Node.js in their projects.

Thank you for your hard work on this plugin!

Best regards,

**Comment by Milanzor** [comment]
Hi there,

I've just released version 3.0.0 by your request. The code worked fine on Node 20 and Node 21 but the package.json did not include those versions.

https://github.com/Milanzor/webpack-watched-glob-entries-plugin/releases/tag/3.0.0

I did, however, have to drop support for Node 12 due to a dependency, for this reason I had to bump the version up to 3.0.0 because it is a breaking change for anyone still using Node 12.

Good luck!

**Comment by yamadashy** [comment]
Thanks again for your quick and efficient work on this. It's greatly appreciated. wishing you a wonderful holiday season !
